services:
  - type: web
    name: resume-analyzer-ai
    env: python
    buildCommand: |
      apt-get update && apt-get install -y gcc
      pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildFilter:
      paths:
        - backend/*
